# Generated by Django 5.2.4 on 2025-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'To-Do',
                'verbose_name_plural': 'To-Dos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['due_date'], name='taskly_todo_due_dat_8b4c4e_idx')],
            },
        ),
    ]
